const cuisineTranslations = {
	afghan: 'Afghanisch',
	african: 'Afrikanisch',
	albanian: 'Albanisch',
	algerian: 'Algerisch',
	american: 'Amerikanisch',
	arabic: 'Arabisch',
	argentinian: 'Argentinisch',
	armenian: 'Armenisch',
	asian: 'Asiatisch',
	australian: 'Australisch',
	austrian: 'Österreichisch',
	bangladeshi: 'Bangladeschisch',
	belgian: 'Belgisch',
	brazilian: 'Brasilianisch',
	british: 'Britisch',
	bulgarian: 'Bulgarisch',
	burmese: 'Burmesisch',
	cambodian: 'Kambodschanisch',
	canadian: 'Kanadisch',
	caribbean: 'Karibisch',
	central_european: 'Mitteleuropäisch',
	chinese: 'Chinesisch',
	colombian: 'Kolumbianisch',
	croatian: 'Kroatisch',
	cuban: 'Kubanisch',
	czech: 'Tschechisch',
	danish: 'Dänisch',
	dutch: 'Niederländisch',
	egyptian: 'Ägyptisch',
	english: 'Englisch',
	ethiopian: 'Äthiopisch',
	european: 'Europäisch',
	filipino: 'Philippinisch',
	finnish: 'Finnisch',
	french: 'Französisch',
	georgian: 'Georgisch',
	german: 'Deutsch',
	greek: 'Griechisch',
	haitian: 'Haitianisch',
	hawaiian: 'Hawaiianisch',
	hungarian: 'Ungarisch',
	icelandic: 'Isländisch',
	indian: 'Indisch',
	indonesian: 'Indonesisch',
	iranian: 'Iranisch',
	iraqi: 'Irakisch',
	irish: 'Irisch',
	israeli: 'Israelisch',
	italian: 'Italienisch',
	jamaican: 'Jamaikanisch',
	japanese: 'Japanisch',
	jordanian: 'Jordanisch',
	korean: 'Koreanisch',
	kurdish: 'Kurdisch',
	lebanese: 'Libanesisch',
	libyan: 'Libysch',
	lithuanian: 'Litauisch',
	malaysian: 'Malaysisch',
	mediterranean: 'Mediterran',
	mexican: 'Mexikanisch',
	middle_eastern: 'Nahöstlich',
	mongolian: 'Mongolisch',
	moroccan: 'Marokkanisch',
	nepalese: 'Nepalesisch',
	new_zealand: 'Neuseeländisch',
	nigerian: 'Nigerianisch',
	norwegian: 'Norwegisch',
	pakistani: 'Pakistanisch',
	palestinian: 'Palästinensisch',
	peruvian: 'Peruanisch',
	polish: 'Polnisch',
	portuguese: 'Portugiesisch',
	romanian: 'Rumänisch',
	russian: 'Russisch',
	salvadorian: 'Salvadorianisch',
	saudi: 'Saudi-Arabisch',
	scandinavian: 'Skandinavisch',
	scottish: 'Schottisch',
	serbian: 'Serbisch',
	singaporean: 'Singapurisch',
	slovak: 'Slowakisch',
	slovenian: 'Slowenisch',
	somali: 'Somalisch',
	south_african: 'Südafrikanisch',
	spanish: 'Spanisch',
	sri_lankan: 'Sri-Lankisch',
	sudanese: 'Sudanesisch',
	swedish: 'Schwedisch',
	swiss: 'Schweizerisch',
	syrian: 'Syrisch',
	taiwanese: 'Taiwanesisch',
	tajik: 'Tadschikisch',
	thai: 'Thailändisch',
	tibetan: 'Tibetisch',
	tunisian: 'Tunesisch',
	turkish: 'Türkisch',
	ukrainian: 'Ukrainisch',
	asparagus: 'Spargel',
	uruguayan: 'Uruguayisch',
	uzbek: 'Usbekisch',
	venezuelan: 'Venezolanisch',
	vietnamese: 'Vietnamesisch',
	welsh: 'Walisisch',
	west_african: 'Westafrikanisch',
	yemeni: 'Jemenitisch',
	regional: 'Regional',
	bavarian: 'Bayrisch',
	pizza: 'Pizza',
	balkan: 'Balkanisch',
	steak_house: 'Steakhaus',
	fish: 'Fischrestaurant',
	suisse: 'Schweizerisch',
	local: 'Regional',
	pasta: 'Pasta',
	noodles: 'Nudeln',
	noodle: 'Nudeln',
	deli: 'Feinkost',
	barbecue: 'Grill',
	international: 'International',
	latin_american: 'Lateinamerikanisch',
	chicken: 'Hähnchen',
	kebab: 'Kebab',
	tacos: 'Tacos',
	ramen: 'Ramen',
	sushi: 'Sushi',
	ice_cream: 'Speiseeis',
	falafel: 'Falafel',
	sausage: 'Wurst',
	persian: 'Persisch',
	coffee_shop: 'Café',
	oriental: 'Orientalisch',
	nikkei: 'Peruanisch-japanische Fusionsküche',
	crepe: 'Crêpes',
	burger: 'Burger',
	breakfast: 'Frühstück',
	alsatian: 'Elsässisch',
	fine_dining: 'Fine Dining',
	cake: 'Kuchen',
	seafood: 'Fisch',
	sandwich: 'Sandwich',
	soup: 'Suppe',
	salad: 'Salat',
	quiche: 'Quiche',
	fries: 'Pommes',
	arab: 'Arabisch',
	fusion: 'Fusionsküche',
	dumplings: 'Teigtaschen',
	nepal: 'Nepalesisch',
	tapas: 'Tapas',
	seasonal: 'Saisonal',
	italian_pizza: 'Italienische Pizza',
	singapurian: 'Singapurisch',
	sri_lanka: 'Sri Lankisch',
	jewish: 'Jüdisch',
	soul_food: 'Soul Food',
	friture: 'Frittiertes',
	swabian: 'Schwäbisch',
	bowl: 'Bowl',
	thuringian: 'Thüringisch',
	'turkish breakfast': 'Türkisches Frühstück',
	eastern_european: 'Osteuropäisch',
	macedonian: 'Mazedonisch',
	anatolian: 'Anatolisch',
	'nepal, himalaya': 'Himalayanisch',
	no: 'Keine Informationen vorhanden',
	'seasonal regional dishes & selected meals with indian touch':
		'saisonale regionale Gerichte & ausgewählte Gerichte mit indischem Touch',
};

export default function CuisineBlock({ tags }) {
	const cuisineRaw = tags['cuisine'];

	if (!cuisineRaw) return null;

	const cuisines = cuisineRaw
		.split(';')
		.map((item) => item.trim().toLowerCase());

	const translated = cuisines.map((key) => cuisineTranslations[key] || key);

	return <h3>{translated.join(', ')}</h3>;
}
